# Change these first
owner: Spotflow-One # Your GitHub organization or username, where this repository lives
repo: private-status # The name of this repository

sites:
  - name: Ledger
    url: https://ledger-api.spotflow.co/
    expectedStatusCodes:
      - 401
  
  - name: Oracle
    url: http://spotflow-oracle-alb-1585543804.us-east-2.elb.amazonaws.com/actuator/health
  
  - name: Exchange
    url: http://spotflow-exchange-alb-1925864159.us-east-2.elb.amazonaws.com/actuator/health
  
  - name: Onchain
    url: http://spotflow-onchain-alb-464868419.us-east-2.elb.amazonaws.com/actuator/health
  
  - name: Notification
    url: http://spotflow-notification-alb-1735256641.us-east-2.elb.amazonaws.com/actuator/health
  
  - name: Gateway
    url: http://spotflow-prod-nlb-c01741dfe9a9375b.elb.us-east-2.amazonaws.com/actuator/health
    
  - name: Accounts
    url: http://spotflow-accounts-alb-918808033.us-east-2.elb.amazonaws.com/actuator/health
    
  - name: Hyperrail-User
    url: http://hyperrail-user-alb-130860453.us-east-2.elb.amazonaws.com/actuator/health
  
  - name: Admin API
    url: https://admin-api.spotflow.co/api-docs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /private-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Spotflow
  introTitle: "Spotflow Status Page"
  introMessage: This is a status page which uses **real-time** data 
  navbar:
    - title: Status
      href: /
  theme: dark
runner: "[self-hosted, Linux, X64, spotflow, prod, general]"


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
